### PR TITLE
Add ability to provide an executable instead of downloading it

### LINKED ISSUE #15: Other version of typst-preview binary
First of all, thank you for your execellent plugin.

I recently find this plugin dosen't work with my typst file. But the vscode plugin works fine.

Then I came up with a hack, which is replacing the one in `vim.fn.stdpath 'data' .. '/typst-preview/` by the vscode one. And it works.

I wounder if it can be possible to add a configuration option in `setup()` to set the path of `typst-preview` cli program?

### PR DESCRIPTION
**Pull request by LamprosPitsillos**
```
Watching buffer: 2                                                                            
Could not start dynamically linked executable: /home/inferno/.local/share/nvim/typst-preview/t
ypst-preview-linux-x64                                                                        
NixOS cannot run dynamically linked executables intended for generic                          
linux environments out of the box. For more information, see:                                 
https://nix.dev/permalink/stub-ld       
```
Was getting the above error on NixOs , so i decided to add a way to provide your own executable
Closes #15

### CODE REVIEW

**Review by chomosuke — CHANGES_REQUESTED** [review]
Thank you for working on this.

I would prefer the configuration option to be generalized over both the `typst-preview` binary and the `websocat` binary. Once that's done I'll be happy to merge this :).

**Comment by LamprosPitsillos** [comment]
I tried to break it but seems to be working as expected , please let me know of any other changes needed!

**Comment by LamprosPitsillos** [comment]
Forgot to modify the readme

**Review by LamprosPitsillos — COMMENTED** [review]
I thought it was strange that you used recursion for such a trivial loop but now i see why it was done that way, although i still believe a better solution could be used.

How does this change handle the "not updating when bin is provided" part that i implemented in the loop implementation?

**Comment by chomosuke** [comment]
> How does this change handle the "not updating when bin is provided" part that i implemented in the loop implementation?

`download_bin()` already calls `up_to_date()` which will return `true` if the bin has been provided.

I agree that in that case the messages are not ideal and I will fix that soon.

**Review by chomosuke — APPROVED** [review]
Please let me know if you're happy with my modification to this PR. If you don't see any issues I will go ahead and merge it :).

And thank you for the work!!

**Comment by LamprosPitsillos** [comment]
Other than that slight clarification in the README and docs about the `path` in `dependencies_bin` , everything LGTM!
Thanks for merging!

**Pull request merged**
