### PR TITLE
feat: support for `tinymist preview`

### PR DESCRIPTION
**Pull request by Parsifa1**

### CODE REVIEW

**Comment by Parsifa1** [comment]
Thank you so much :)

**Comment by chomosuke** [comment]
No worries! thank you for your PR too!

**Comment by Scalamando** [comment]
I'm trying to use tinymist with the config below but using the `TypstPreview` command doesn't start the preview and the only debug messages are:

```bash
06:51:53 PM msg_show Usage: tinymist [COMMAND]
06:51:53 PM msg_show For more information, try '--help'.
```
Using the CLI I could only reproduce this by omitting the `preview` command in `tinymist preview` but that shouldn't happen if [this piece of code](https://github.com/chomosuke/typst-preview.nvim/blob/master/lua/typst-preview/servers/factory.lua#L35) is working as intended.

Do you have any idea what's going on?

---
My typst-preview.nvim config:
```lua
  {
    "chomosuke/typst-preview.nvim",
    ft = "typst",
    version = "0.3.*",
    opts = {
      debug = true,
      dependencies_bin = {
        ["typst-preview"] = "tinymist",
      },
    },
    build = function()
      require("typst-preview").update()
    end,
  },
```

**Comment by Parsifa1** [comment]
@Scalamando Are you sure your `tinymist preview` works properly in the shell?

**Comment by Scalamando** [comment]
> Oh, I know, you should delete the `version` lock :)
> this pr is on the master

That was the problem! Thanks for your help and the PR :)

**Pull request merged**
